title: Topcoat
email: garthdb@gmail.com
description: CSS for clean and fast web apps.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://topcoat.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
sass:
  sass_dir: _sass
  style: compressed
permalink: /posts/:title/
authors:
  brianleroux:
    name: "Brian LeRoux"
    twitter: "brianleroux"
    url: "http://brian.io/"
  dam:
    name: "Kristofer Joseph"
    twitter: "dam"
    url: "http://kristoferjoseph.com/"
  garthdb:
    name: "Garth Braithwaite"
    twitter: "garthdb"
    url: "http://www.garthdb.com/"
  nnnnic:
    name: "Nic Couillard"
    twitter: "nnnnic"
    url: "http://nnnnic.com/"
  g1sh:
    name: "Guillermo Torres"
    twitter: "g1sh"
    url: "http://www.g1sh.com/"
  ndreio:
    name: "Andrei Oprea"
    twitter: "ndreio"
    url: "http://github.com/piatra"
  nodoherty:
    name: "Niall O'Doherty"
    twitter: "nodoherty"
    url: "http://github.com/nodoherty"
  chris-perkins:
    name: "Chris Perkins"
    url:  "http://xdk.intel.com"
